name: Cypress Tests on Cypress Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Set up Cypress Cloud environment variables
        run: |
          echo '{"USERNAME": "${{ secrets.CYPRESS_USERNAME }}", "PASSWORD": "${{ secrets.CYPRESS_PASSWORD }}"}' > cypress.env.json
      - name: Run Cypress tests on Cypress Cloud
        run: npx cypress run --record --key e5135b38-e99c-4766-96e2-0b220527b6bc
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
